export interface EcosystemSource {
  id: string;
  name: string;
  category: 'Government / State Agency' | 'Premier Research Incubator' | 'University TBI' | 'Private Accelerator' | 'Angel Network' | 'Regional Ecosystem Hub' | 'Secondary Business Database';
  district: string;
  website: string;
  focusAreas: string[];
  authorityScore: number; // 0 - 100
}

export const ECOSYSTEM_SOURCES_REGISTRY: EcosystemSource[] = [
  // 1. Government & State Bodies
  {
    id: 'src-startuptn',
    name: 'StartupTN (Tamil Nadu Startup and Innovation Mission)',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://startuptn.in',
    focusAreas: ['TANSEED Grants', 'SC/ST Startup Fund', 'Women-led Startups', 'Regional Hubs', 'Smart Agri Hub', 'Green Tech Hub', 'Blue Economy Hub'],
    authorityScore: 100,
  },
  {
    id: 'src-dpiit',
    name: 'Startup India / DPIIT (Department for Promotion of Industry and Internal Trade)',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://www.startupindia.gov.in',
    focusAreas: ['DPIIT Recognition', 'SISFS Seed Fund Scheme', 'Income Tax Exemptions'],
    authorityScore: 100,
  },
  {
    id: 'src-edii-tn',
    name: 'EDII-TN (Entrepreneurship Development and Innovation Institute Tamil Nadu)',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://editn.in',
    focusAreas: ['IVP Innovation Voucher Program', 'Entrepreneurship Training', 'District MSME Support'],
    authorityScore: 95,
  },
  {
    id: 'src-guidance-tn',
    name: 'Guidance Tamil Nadu (Investment Promotion Agency)',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://investingintamilnadu.com',
    focusAreas: ['Industrial Policy', 'EV Policy', 'FinTech Policy', 'R&D Policy'],
    authorityScore: 95,
  },

  // 2. Premier Research Incubators
  {
    id: 'src-iitmic',
    name: 'IIT Madras Incubation Cell (IITMIC) & IITM Research Park',
    category: 'Premier Research Incubator',
    district: 'Chennai',
    website: 'https://incubation.iitm.ac.in',
    focusAreas: ['DeepTech', 'SpaceTech', 'Robotics', 'EV & Energy Storage', 'HealthTech', 'Quantum Computing'],
    authorityScore: 100,
  },
  {
    id: 'src-ciic',
    name: 'Crescent Innovation & Incubation Council (CIIC)',
    category: 'Premier Research Incubator',
    district: 'Chengalpattu',
    website: 'https://ciic.education',
    focusAreas: ['Life Sciences', 'BioTech', 'Industry 4.0', 'Clean Mobility', 'Aerospace'],
    authorityScore: 90,
  },
  {
    id: 'src-forge',
    name: 'Forge Innovation & Ventures (FORGE.FACTORY)',
    category: 'Premier Research Incubator',
    district: 'Coimbatore',
    website: 'https://forge-iv.co',
    focusAreas: ['Industrial Hardware', 'Defense Hardware', 'Production Tech', 'Climate Hardware', 'Mobility'],
    authorityScore: 90,
  },
  {
    id: 'src-aic-raise',
    name: 'AIC-Raise (Atal Incubation Centre - Rathinam)',
    category: 'Premier Research Incubator',
    district: 'Coimbatore',
    website: 'https://aicraise.com',
    focusAreas: ['AI', 'United Nations SDGs', 'EdTech', 'Assistive Tech', 'IoT'],
    authorityScore: 88,
  },
  {
    id: 'src-psg-step',
    name: 'PSG Science & Technology Entrepreneurial Park (PSG-STEP)',
    category: 'Premier Research Incubator',
    district: 'Coimbatore',
    website: 'https://psgstep.org',
    focusAreas: ['Industrial BioTech', 'Nanotechnology', 'Embedded Electronics', 'Healthcare', 'Software'],
    authorityScore: 92,
  },
  {
    id: 'src-vit-tbi',
    name: 'VIT Technology Business Incubator (VITTBI)',
    category: 'University TBI',
    district: 'Vellore',
    website: 'https://vittbi.com',
    focusAreas: ['BioNEST BioTech', 'Robotics', 'AI Diagnostics', 'Urban Air Mobility', 'Tissue Engineering'],
    authorityScore: 90,
  },
  {
    id: 'src-trec-step',
    name: 'TREC-STEP (NIT Tiruchirappalli)',
    category: 'University TBI',
    district: 'Tiruchirappalli',
    website: 'https://trecstep.com',
    focusAreas: ['Manufacturing Automation', 'Clean Energy', 'Environmental Engineering', 'IoT'],
    authorityScore: 88,
  },
  {
    id: 'src-sastra-first',
    name: 'SASTRA TBI (Foundation for Innovation & Research at SASTRA - FIRST)',
    category: 'University TBI',
    district: 'Thanjavur',
    website: 'https://first.sastra.edu',
    focusAreas: ['Additive Manufacturing (3D Printing)', 'IoT', 'Robotics', 'VR Simulation'],
    authorityScore: 88,
  },
  {
    id: 'src-sona-sif',
    name: 'Sona Incubation Foundation (Sona TBI)',
    category: 'University TBI',
    district: 'Salem',
    website: 'https://sonaincubations.com',
    focusAreas: ['Wearable Tech', 'Industry 4.0', 'Medical Devices', 'Fashion Tech', 'Drones'],
    authorityScore: 85,
  },
  {
    id: 'src-kec-tbi',
    name: 'Technology Business Incubator @ Kongu Engineering College (TBI@KEC)',
    category: 'University TBI',
    district: 'Erode',
    website: 'http://www.tbi-kec.org',
    focusAreas: ['Electronics & Embedded Hardware', 'IoT', 'Agri Automation', 'Textile Robotics'],
    authorityScore: 85,
  },
  {
    id: 'src-fx-tbi',
    name: 'Francis Xavier Technology Business Incubator (FX TBI)',
    category: 'University TBI',
    district: 'Tirunelveli',
    website: 'https://francisxavier.ac.in',
    focusAreas: ['AI & ML', 'Rural Tech', 'Renewable Energy', 'AgriTech'],
    authorityScore: 82,
  },
  {
    id: 'src-periyar-tbi',
    name: 'Periyar Technology Business Incubator',
    category: 'University TBI',
    district: 'Thanjavur',
    website: 'https://periyartbi.org',
    focusAreas: ['Bio-processing', 'Agri-waste valorization', 'Rural Women Entrepreneurship'],
    authorityScore: 82,
  },
  {
    id: 'src-iifpt-abi',
    name: 'IIFPT Agri-Business Incubator (NIFTEM-T)',
    category: 'Premier Research Incubator',
    district: 'Thanjavur',
    website: 'https://iifpt.edu.in',
    focusAreas: ['Food Processing', 'Nutraceuticals', 'Millet Formulations', 'Cold Chain Packaging'],
    authorityScore: 90,
  },
  {
    id: 'src-tnau-abis',
    name: 'TNAU Agri-Business Incubation Society (ABIS-TBI)',
    category: 'University TBI',
    district: 'Coimbatore',
    website: 'https://tbitnau.com',
    focusAreas: ['Organic Bio-inputs', 'Moringa Valorization', 'BSF Larvae Pet Feed', 'Farm Machinery'],
    authorityScore: 90,
  },
  {
    id: 'src-au-tbi',
    name: 'Anna University Centre for Biotechnology & AU-TBI',
    category: 'University TBI',
    district: 'Chennai',
    website: 'https://annauniv.edu',
    focusAreas: ['Industrial Enzymes', 'Biomedical Diagnostic Kits', 'Software'],
    authorityScore: 88,
  },
  {
    id: 'src-veltech-tbi',
    name: 'Vel Tech Technology Business Incubator',
    category: 'University TBI',
    district: 'Tiruvallur',
    website: 'https://veltechtbi.com',
    focusAreas: ['Automotive Electronics', 'Defense Avionics', '3D Prototyping'],
    authorityScore: 85,
  },
  {
    id: 'src-srm-siic',
    name: 'SRM Innovation and Incubation Centre (SIIC)',
    category: 'University TBI',
    district: 'Chengalpattu',
    website: 'https://srmist.edu.in',
    focusAreas: ['Healthcare Robotics', 'Clean Energy', 'AI / FinTech'],
    authorityScore: 85,
  },
  {
    id: 'src-sathyabama-tbi',
    name: 'Sathyabama Technology Business Incubator',
    category: 'University TBI',
    district: 'Chengalpattu',
    website: 'https://sathyabama.ac.in',
    focusAreas: ['Marine Bio-products', 'Nano-materials', 'Defense Tech'],
    authorityScore: 82,
  },
  {
    id: 'src-kalasalingam-tbi',
    name: 'Kalasalingam University TBI (KARE-TBI)',
    category: 'University TBI',
    district: 'Virudhunagar',
    website: 'https://kalasalingam.ac.in',
    focusAreas: ['Packaging Automation', 'Fireworks Safety Tech', 'AgriTech'],
    authorityScore: 80,
  },
  {
    id: 'src-st-xaviers-tbi',
    name: 'St. Xavier’s Catholic College Innovation Center',
    category: 'University TBI',
    district: 'Kanyakumari',
    website: 'https://sxcce.edu.in',
    focusAreas: ['Renewable Energy', 'Marine Tech', 'Software & Remote Tech'],
    authorityScore: 80,
  },
  {
    id: 'src-cecri-karaikudi',
    name: 'CSIR - Central Electrochemical Research Institute (CECRI) Innovation Hub',
    category: 'Premier Research Incubator',
    district: 'Sivaganga',
    website: 'https://cecri.res.in',
    focusAreas: ['Advanced Batteries', 'Lithium / Sodium-ion Cells', 'Corrosion Prevention', 'Graphite Tech'],
    authorityScore: 95,
  },
  {
    id: 'src-tnjfu-abi',
    name: 'Tamil Nadu Dr. J. Jayalalithaa Fisheries University Incubation (TNJFU-ABI)',
    category: 'University TBI',
    district: 'Nagapattinam',
    website: 'https://tnjfu.ac.in',
    focusAreas: ['Marine Aquaculture', 'Seaweed Biostimulants', 'Smart Fish Feed Systems'],
    authorityScore: 85,
  },
  {
    id: 'src-tanuvas-tbi',
    name: 'TANUVAS Veterinary Incubation Cell',
    category: 'University TBI',
    district: 'Namakkal',
    website: 'https://tanuvas.ac.in',
    focusAreas: ['Poultry Health Diagnostics', 'Smart Livestock Monitoring', 'Dairy IoT'],
    authorityScore: 85,
  },
  {
    id: 'src-tce-tbi',
    name: 'Thiagarajar College of Engineering TBI (TCE TBI)',
    category: 'University TBI',
    district: 'Madurai',
    website: 'https://tce.edu',
    focusAreas: ['DeepTech', 'Smart Sensors', 'Water Monitoring', 'Agritech'],
    authorityScore: 85,
  },

  // 3. Angel Networks & Early Stage Investors
  {
    id: 'src-tca',
    name: 'The Chennai Angels (TCA)',
    category: 'Angel Network',
    district: 'Chennai',
    website: 'https://thechennaiangels.com',
    focusAreas: ['SaaS', 'DeepTech', 'FinTech', 'HealthTech', 'D2C Consumer Brands'],
    authorityScore: 92,
  },
  {
    id: 'src-nativelead',
    name: 'Nativelead Foundation & Native Angels Network (NAN)',
    category: 'Angel Network',
    district: 'Madurai',
    website: 'https://nativelead.org',
    focusAreas: ['Tier 2/3 District Startups', 'Agritech', 'Rural D2C', 'CleanTech', 'Madurai, Coimbatore, Trichy, Karur, Erode, Tuticorin'],
    authorityScore: 90,
  },
  {
    id: 'src-speciale',
    name: 'Speciale Invest',
    category: 'Private Accelerator',
    district: 'Chennai',
    website: 'https://specialeinvest.com',
    focusAreas: ['SpaceTech', 'DeepTech Hardware', 'Photonics', 'Advanced Materials'],
    authorityScore: 90,
  },
  {
    id: 'src-tie-chennai',
    name: 'TiE Chennai (The Indus Entrepreneurs)',
    category: 'Regional Ecosystem Hub',
    district: 'Chennai',
    website: 'https://chennai.tie.org',
    focusAreas: ['Mentorship', 'Pitch Competitions', 'Ecosystem Scaling'],
    authorityScore: 88,
  },

  // 4. Secondary Startup Databases & News Portals
  {
    id: 'src-inc42',
    name: 'Inc42 Startup Intelligence',
    category: 'Secondary Business Database',
    district: 'Chennai',
    website: 'https://inc42.com',
    focusAreas: ['Funding Rounds', 'Unicorn & Soonicorn Tracking', 'Tamil Nadu Startup Ecosystem Reports'],
    authorityScore: 78,
  },
  {
    id: 'src-yourstory',
    name: 'YourStory Media',
    category: 'Secondary Business Database',
    district: 'Chennai',
    website: 'https://yourstory.com',
    focusAreas: ['Founder Profiles', 'Grassroots Innovation', 'Tier 2/3 Tamil Nadu Founders'],
    authorityScore: 78,
  },
  {
    id: 'src-tracxn',
    name: 'Tracxn Technologies',
    category: 'Secondary Business Database',
    district: 'Chennai',
    website: 'https://tracxn.com',
    focusAreas: ['Cap Table Analysis', 'Startup Institutional Rounds', 'Patent Analytics'],
    authorityScore: 80,
  },
  {
    id: 'src-thehindu-bl',
    name: 'The Hindu Business Line Startup Coverage',
    category: 'Secondary Business Database',
    district: 'Chennai',
    website: 'https://thehindubusinessline.com',
    focusAreas: ['Policy Updates', 'StartupTN Grants', 'Regional Enterprise News'],
    authorityScore: 82,
  },
];
