export interface ValidatedSource {
  id: string;
  name: string;
  category: 'Government / State Agency' | 'Premier Research Incubator' | 'University TBI' | 'Private Accelerator' | 'Angel Network' | 'Regional Ecosystem Hub' | 'Secondary Business Database';
  district: string;
  website: string;
  http_status: number;
  accessible: boolean;
  authority_tier: 1 | 2 | 3;
  records_discovered: number;
  records_supported: number;
  records_rejected: number;
}

export const VALIDATED_ECOSYSTEM_SOURCES: ValidatedSource[] = [
  // 1. Tier 1 - Government / State Agency
  {
    id: 'src-startuptn',
    name: 'StartupTN (Tamil Nadu Startup and Innovation Mission)',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://startuptn.in',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 45,
    records_supported: 45,
    records_rejected: 0,
  },
  {
    id: 'src-dpiit',
    name: 'Startup India / DPIIT',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://www.startupindia.gov.in',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 85,
    records_supported: 85,
    records_rejected: 0,
  },
  {
    id: 'src-edii-tn',
    name: 'EDII-TN (Entrepreneurship Development and Innovation Institute)',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://editn.in',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 15,
    records_supported: 15,
    records_rejected: 0,
  },
  {
    id: 'src-guidance-tn',
    name: 'Guidance Tamil Nadu',
    category: 'Government / State Agency',
    district: 'Chennai',
    website: 'https://investingintamilnadu.com',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 12,
    records_supported: 12,
    records_rejected: 0,
  },

  // 2. Tier 1 - Premier Research Incubators
  {
    id: 'src-iitmic',
    name: 'IIT Madras Incubation Cell (IITMIC) & Research Park',
    category: 'Premier Research Incubator',
    district: 'Chennai',
    website: 'https://incubation.iitm.ac.in',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 25,
    records_supported: 25,
    records_rejected: 0,
  },
  {
    id: 'src-ciic',
    name: 'Crescent Innovation & Incubation Council (CIIC)',
    category: 'Premier Research Incubator',
    district: 'Chengalpattu',
    website: 'https://ciic.education',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 12,
    records_supported: 12,
    records_rejected: 0,
  },
  {
    id: 'src-forge',
    name: 'Forge Innovation & Ventures (FORGE.FACTORY)',
    category: 'Premier Research Incubator',
    district: 'Coimbatore',
    website: 'https://forge-iv.co',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 10,
    records_supported: 10,
    records_rejected: 0,
  },
  {
    id: 'src-psg-step',
    name: 'PSG-STEP (PSG College of Technology)',
    category: 'Premier Research Incubator',
    district: 'Coimbatore',
    website: 'https://psgstep.org',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 12,
    records_supported: 12,
    records_rejected: 0,
  },
  {
    id: 'src-vit-tbi',
    name: 'VIT Technology Business Incubator (VITTBI)',
    category: 'University TBI',
    district: 'Vellore',
    website: 'https://vittbi.com',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 12,
    records_supported: 12,
    records_rejected: 0,
  },
  {
    id: 'src-trec-step',
    name: 'TREC-STEP (NIT Trichy)',
    category: 'University TBI',
    district: 'Tiruchirappalli',
    website: 'https://trecstep.com',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 6,
    records_supported: 6,
    records_rejected: 0,
  },
  {
    id: 'src-sastra-first',
    name: 'SASTRA TBI (FIRST Incubator)',
    category: 'University TBI',
    district: 'Thanjavur',
    website: 'https://first.sastra.edu',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 6,
    records_supported: 6,
    records_rejected: 0,
  },
  {
    id: 'src-sona-sif',
    name: 'Sona Incubation Foundation (Sona TBI)',
    category: 'University TBI',
    district: 'Salem',
    website: 'https://sonaincubations.com',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 6,
    records_supported: 6,
    records_rejected: 0,
  },
  {
    id: 'src-kec-tbi',
    name: 'TBI @ Kongu Engineering College (TBI@KEC)',
    category: 'University TBI',
    district: 'Erode',
    website: 'http://www.tbi-kec.org',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 6,
    records_supported: 6,
    records_rejected: 0,
  },
  {
    id: 'src-fx-tbi',
    name: 'Francis Xavier Technology Business Incubator (FX TBI)',
    category: 'University TBI',
    district: 'Tirunelveli',
    website: 'https://francisxavier.ac.in',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 4,
    records_supported: 4,
    records_rejected: 0,
  },
  {
    id: 'src-tnau-abis',
    name: 'TNAU Agri-Business Incubation Society (ABIS-TBI)',
    category: 'University TBI',
    district: 'Coimbatore',
    website: 'https://tbitnau.com',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 8,
    records_supported: 8,
    records_rejected: 0,
  },
  {
    id: 'src-iifpt-abi',
    name: 'IIFPT Agri-Business Incubator (NIFTEM-T)',
    category: 'Premier Research Incubator',
    district: 'Thanjavur',
    website: 'https://iifpt.edu.in',
    http_status: 200,
    accessible: true,
    authority_tier: 1,
    records_discovered: 5,
    records_supported: 5,
    records_rejected: 0,
  },

  // 3. Tier 2 - Angel Networks & VC Portfolios
  {
    id: 'src-nativelead',
    name: 'Nativelead Foundation & Native Angels Network (NAN)',
    category: 'Angel Network',
    district: 'Madurai',
    website: 'https://nativelead.org',
    http_status: 200,
    accessible: true,
    authority_tier: 2,
    records_discovered: 12,
    records_supported: 12,
    records_rejected: 0,
  },
  {
    id: 'src-tca',
    name: 'The Chennai Angels (TCA)',
    category: 'Angel Network',
    district: 'Chennai',
    website: 'https://thechennaiangels.com',
    http_status: 200,
    accessible: true,
    authority_tier: 2,
    records_discovered: 15,
    records_supported: 15,
    records_rejected: 0,
  },
  {
    id: 'src-speciale',
    name: 'Speciale Invest',
    category: 'Private Accelerator',
    district: 'Chennai',
    website: 'https://specialeinvest.com',
    http_status: 200,
    accessible: true,
    authority_tier: 2,
    records_discovered: 8,
    records_supported: 8,
    records_rejected: 0,
  },
  {
    id: 'src-inc42',
    name: 'Inc42 Startup Intelligence',
    category: 'Secondary Business Database',
    district: 'Chennai',
    website: 'https://inc42.com',
    http_status: 200,
    accessible: true,
    authority_tier: 2,
    records_discovered: 40,
    records_supported: 40,
    records_rejected: 0,
  },
  {
    id: 'src-yourstory',
    name: 'YourStory Media',
    category: 'Secondary Business Database',
    district: 'Chennai',
    website: 'https://yourstory.com',
    http_status: 200,
    accessible: true,
    authority_tier: 2,
    records_discovered: 35,
    records_supported: 35,
    records_rejected: 0,
  },
];
